spring:
  application:
    name: zzwm

  # DB configuration
  datasource:
    username: zzwm
    password: Abc@123456
    url: jdbc:mysql://localhost:3306/zzwm?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      connection-test-query: SELECT 1

  # JPA configuration
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
          fetch_size: 100
  data:
    redis:
      host: localhost
      port: 6379
      password: Abc@123456

# springdoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: false
    supported-submit-methods:
  api-docs:
    path: /v3/api-docs


# logging
logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
